### PR TITLE
Added Module classes

### PR DESCRIPTION
**Pull request by LHR07-DBz**
mx.modules.Module; 
mx.events.ModuleEvent; 
mx.modules.IModule; 
mx.core.LayoutContainer; 
mx.modules.ModuleLoader; 
mx.modules.ModuleManagerGlobals; 
mx.modules.ModuleManager;

### CODE REVIEW

**Comment by LHR07-DBz** [comment]
Files updated as per instruction

**Comment by alinakazi** [comment]
ModuleEvent should extend Event

**Comment by LHR07-DBz** [comment]
Done. ModuleEvent extends ProgressEvent

**Comment by LHR07-DBz** [comment]
Moved references from MXRoyaleClasses.as to mx-manifest.xml

**Pull request merged**
