### PR TITLE
XML - Copy blank attribute values.

### PR DESCRIPTION
**Pull request by estanglerbm**
Undoing a change made by @harbs in commit 6664fb4bb5308b376ba269635a48e63ba729ba7b.

### CODE REVIEW

**Comment by Harbs** [comment]
This causes empty attributes to use more memory.

That commit made a very big difference in memory usage of XML. The values are not being set on purpose.

**Comment by Harbs** [comment]
In fact, we're probably setting empty values in more places than we should.

**Comment by Harbs** [comment]
Resolved in 4c4e9ee4e5f69d30b8bf25f3b236cf35aae70c4c

**Comment by estanglerbm** [comment]
To be clear, you're talking about excessive memory usage because there are many empty strings (as part of parsing XML using DOMParser.parseFromString) besides attributes.

**Comment by Harbs** [comment]
Exactly.

My use case made extensive use of `copy`, so fixing it in `copy` made a big difference. I should have done a better job on the optimization the first time around... 😉

**Pull request closed without merging**
