### PR TITLE
Helper function to remove event listener without the need for casting

### PR DESCRIPTION
**Pull request by SolidSoft-Lda**

### CODE REVIEW

**Comment by Harbs** [comment]
Because of PAYG, we don't want to add a remove function directly to Bead.

A stand alone utility function is better for this.

Thanks!
Harbs

**Comment by carlosrovira** [comment]
Hugo, is easy to change to a stand alone function, you have lots of examples in Royale.
Thanks

**Comment by SolidSoft-Lda** [comment]
Yeah, it's not a big issue for me. I had the feeling that was incomplete because we already have the add event listener helper anyway, but, it's ok for me. I understand that PAYG have rules.

**Comment by Harbs** [comment]
I'm hoping we can get to the point where PAYG wil be helped by the compiler and unused methods can be stripped out of compiled apps. We're not yet sure that's going to be possible, so we need to be stricter than would otherwise be ideal.

Here's more info for your reading pleasure. 😄 https://github.com/apache/royale-asjs/issues/641

**Comment by SolidSoft-Lda** [comment]
Very cool :)

**Comment by carlosrovira** [comment]
yeah that would be super awesome to get implemented in the compiler :)
I read that some js tech out there already does it, so I think it's completely possible for Royale too.
Just we need the proper muscle to get it done as always :)

**Pull request closed without merging**
