### PR TITLE
Various small fixes and changes

### PR DESCRIPTION
**Pull request by estanglerbm**
Various small fixes and changes.

### CODE REVIEW

**Comment by estanglerbm** [comment]
Updated to remove unused MX VirtualListVerticalLayout.

**Comment by estanglerbm** [comment]
Updated to fix issues in DataItemRendererFactoryForIListData.dataProviderChangeHandler().  [It was conflicting with its super.]

**Comment by estanglerbm** [comment]
Updated to fix this pointer in last set of changes.

**Comment by estanglerbm** [comment]
Don't forget about these fixes.

**Comment by estanglerbm** [comment]
Moved some (non-MX) changes to PR #1150.

**Comment by Harbs** [comment]
Thanks!

**Pull request merged**
