### PR TITLE
Fix navigationlink href value always being #

### PR DESCRIPTION
**Pull request by mrvx23**
NavigationLinkItemRender reads the href value of the link out of it's data object .href property.

Expected:
NavigationLinkItemRenderer gets compiled into an anchor tag with the specified href value.

Actual:
NavigationLinkItemRenderer gets compiled into an anchor tag with href="#".

This is due to the internal logic of processing the href value, which seems to have broken due to indirect changes in (parent?) components. Href is only considered if an internal textNode is present, but in reality, the anchor tag and the child textNode should be handled independently.

### CODE REVIEW

**Comment by carlosrovira** [comment]
Hi this PR seems to be mixed and with duplicates. Can you please redo it so I can review it. 
Thanks!

**Comment by piotrzarzycki21** [comment]
@mrvx23 Did you build TourDeJewel and check whether there is no changes in UI due to those changes ?

**Comment by mrvx23** [comment]
@piotrzarzycki21 you're right, after checking I see that this breaks the navigation drawer in TourDeJewel.

The problem is that the 'href' property can possibly be used for two purposes:

1. To identify the navigation section for the change handler, so that the correct section can be made visible (= "internal link"), and
2. To act as a standard link/anchor reference, to support deep linking with URL in a Royale application.

Obviously 2) is currently not functional in develop branch, but at some point it used to be supported, as there is (dead) logic there to set the a.href to another value than '#'.

Solution proposal:
Inspect the incoming href value. Determine if it's an absolute or relative link. If it starts with http:// or https://, treat it as an absolute link and pass it through to the anchor tag.
Otherwise, treat it as a relative link, and inspect if it starts with prefix '#'. If it does not start, add the prefix '#'. This creates backwards compatibility for existing code (like TourDeJewel) that rely on href as an internal link.

**Comment by mrvx23** [comment]
I committed also the proposed fix for backwards compatibility. Note that browser URL will still reflect the new fragment, but this will not break standard Navigation usage.

Please see the change under Files changed tab. The commit history got a little mixed up, but you will see it's only the single file that's changed. If you prefer, I can try creating a new pull request with a single commit.

**Comment by piotrzarzycki21** [comment]
@mrvx23 Well I'm not a fun of checking whether some string has searched value or not. Maybe in that case this is the only solution. How my link should behave if user put's there "ftp://" ?

**Comment by piotrzarzycki21** [comment]
> Hi this PR seems to be mixed and with duplicates. Can you please redo it so I can review it.
> Thanks!

What commits are mixed ? I see that this PR contains stuff which is not accepted yet from other PR (https://github.com/apache/royale-asjs/pull/576) - is this what you are referring to ?

**Comment by mrvx23** [comment]
Right, and also case differences could through it off (e.g. HTTP://). Perhaps the most generic solution is a regex like https://stackoverflow.com/questions/10687099/how-to-test-if-a-url-string-is-absolute-or-relative/19709846#19709846

**Comment by mrvx23** [comment]
Closing, as pull request has mixed commits.

**Comment by carlosrovira** [comment]
Hi @mrvx23, I think this is solved now, since recently I removed `href` since as you said was never used after other changes some months ago. I removed it to make Router class work with Jewel. Thanks for closing it. Please let me know if you find any other issue.

**Comment by mrvx23** [comment]
Great to hear it's fixed, thanks for the followup, @carlosrovira !

**Pull request closed without merging**
