### PR TITLE
Have date chooser dispatch month change events

### PR DESCRIPTION
**Pull request by justinmclean**
Example code:
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic">

    <fx:Script><![CDATA[
        public function monthChange():void {
            trace("month changed");
        }
        ]]></fx:Script>

    <js:beads>
        <js:ApplicationDataBinding />
    </js:beads>

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View>
            <js:Group id="content" height="200" width="250">
                <js:beads>
                    <js:VerticalLayout />
                </js:beads>
                <js:DateChooser id="dc1" height="200" monthChanged="monthChange()" />
            </js:Group>
        </js:View>
    </js:initialView>

</js:Application>

### CODE REVIEW

**Comment by justinmclean** [comment]
Note as other pull request have not been accepted yet this pull request contains some extra changes and my need to be modified. I can't see any easy way of fixing this as those changes were made in my develop branch.

**Comment by pentapache** [comment]
I'm looking over the changes. Why does "displayedMonthChanged" need to change to "monthChanged"? I know that adding the [Event] metadata to DateChooser is necessary, but I don't see why the event names had to change. Was there a conflict?

**Comment by justinmclean** [comment]
To make the event handler name more in line with other event handler names.

**Comment by justinmclean** [comment]
Reopens as PR #100 to remove commit history.

**Pull request closed without merging**
