### PR TITLE
Correction of the text of some constants and 12 new ones.

### PR DESCRIPTION
**Pull request by mjesteve**

### CODE REVIEW

**Comment by Harbs** [comment]
The changes don't look right. See here: https://gist.github.com/zaucy/7c735998565b53f1bed9

Does newer versions of Font Awesome use different selectors? If so, maybe it's more appropriate to create new constants for those.

**Comment by carlosrovira** [comment]
Hi  @Harbs, this ones are for FA5 (as the name of the class states. Maybe the ones from zaucy are for FA4?, we have other file for FA4 constants

**Comment by Harbs** [comment]
In that case, doesn't it make sense to rename the constant names as well?

**Comment by Harbs** [comment]
i.e. I'd expect either:
`public static const SORT_ALPHA_ASC:String = "sort-alpha-asc";`
or `public static const SORT_ALPHA_UP:String = "sort-alpha-up";`
If `sort-alpha-up` is the only proper value for FA5, I'd think we should only have the second version.

**Comment by Harbs** [comment]
Is there a reason to mix and match the values that I'm not understanding?

**Comment by mjesteve** [comment]
I thought it would be better to respect the current constants, but really in FA5 there is no "sort-alpha-asc" or "sort-numeric-asc" ... Do I change it?

**Comment by Harbs** [comment]
Yes. I think so. It seems confusing to have a different constant name than what FA requires. 

Thanks for the PR! :)

**Comment by carlosrovira** [comment]
Yeah, const must match strings since otherway are confusingt.
thanks

**Comment by mjesteve** [comment]
> Yeah, const must match strings since otherway are confusingt.
> thanks

¿Is Ok?

**Comment by Harbs** [comment]
Perfect. Thanks!

**Pull request merged**
