### PR TITLE
TitleWindow and ColorPicker Added

### PR DESCRIPTION
**Pull request by LHR07-DBz**

### CODE REVIEW

**Comment by alinakazi** [comment]
line no. 44 and 45 in TitleWindow
//[Event(name="close", type="mx.events.CloseEvent")]
import org.apache.royale.events.CloseEvent;

Bring import org.apache.royale.events.CloseEvent; on top with other imports 
and uncomment close event as it is in the API List : mx.containers.TitleWindow:close 	

also replace  @productversion Flex 3/Flex 4 with Latest Royale Version 
e.g @productversion Royale 0.9.3

Comment all datamembers/methods in ColorPicker 
except mx.controls.ColorPicker 	
mx.controls.ColorPicker:height 
mx.controls.ColorPicker:selectedColor 	
mx.controls.ColorPicker:width 	
mx.controls.ColorPicker:x 	
mx.controls.ColorPicker:y 	
Like : dropdownGap, indexFlag:Boolean  initializing etc should be commented in ColorPicker.as

**Comment by LHR07-DBz** [comment]
Both files modified as per comments

**Comment by alinakazi** [comment]
CornerRadius is a property that is required in TitleWindow. As the property is extended from Panel so uncomment cornerRadius property in Panel. CornerRadius  is just an example.Also check all other properties and methods.
In Panel
//[Style(name="cornerRadius", type="Number", format="Length", inherit="no", theme="halo, spark")]

mx.containers.TitleWindow:bottom 	
mx.containers.TitleWindow:close 	
**mx.containers.TitleWindow:cornerRadius** 	
mx.containers.TitleWindow:creationComplete 	
mx.containers.TitleWindow:creationPolicy 	
mx.containers.TitleWindow:dropShadowVisible 	
mx.containers.TitleWindow:fontWeight 	
mx.containers.TitleWindow:height 	
mx.containers.TitleWindow:horizontalAlign 	
mx.containers.TitleWindow:layout 	
mx.containers.TitleWindow:minHeight 	
mx.containers.TitleWindow:paddingBottom 	
mx.containers.TitleWindow:paddingLeft 	
mx.containers.TitleWindow:paddingRight 	
mx.containers.TitleWindow:paddingTop 	
mx.containers.TitleWindow:showCloseButton 	
mx.containers.TitleWindow:title 	
mx.containers.TitleWindow:top 	
mx.containers.TitleWindow:verticalAlign 	
mx.containers.TitleWindow:width 	
mx.containers.TitleWindow:x

**Comment by LHR07-DBz** [comment]
Moved references from MXRoyaleClasses.as to mx-manifest.xml

**Pull request merged**
