### PR TITLE
Date chooser no year check

### PR DESCRIPTION
**Pull request by justinmclean**
As the calendar doesn't span months their is no need to check if the years are the same or oddly that the year is non zero as the code was currently doing.

### CODE REVIEW

**Comment by Harbs** [comment]
The year comparison is necessary because the month of the following year can be displayed.

The code seemed to be missing the second half of the year equality check.

toDateString() and caching the _selectedDate date string is a probably a more efficient way of doing this check and definitely simpler.

**Comment by justinmclean** [comment]
One one month at a time is displayed so how can the note of the following year be displayed? If the month of the following year is displayed then the month has changed to 1 from 12 so the year check is not required. Please merge the pull request.

**Comment by Harbs** [comment]
This is a moot point because the change I made makes the whole question an academic one, but, to answer your point:

The selectedDate should not change when displaying a different month. Imagine October 29 2017 is selected. The user then pages through the months to October 2018. This does not change the selected date. The logic needs to differentiate between October 29 2017 and October 29 2018 and not display October 29 2018 as the selected date.

There appears to be a bug in the display where the selected date is not shown when coming back to that month, but that is a separate issue.

**Comment by justinmclean** [comment]
If want to include the year check then this would be a lot more efficient than the original code.
```
        public function getIndexForSelectedDate():Number
        {
            var d:Date = _selectedDate;
            if (d == null || _days[0].getFullYear() != d.getFullYear() || _days[0].getMonth() == d.getMonth()) return -1;
            
            for(var i:int=0; i < _days.length; i++) {
                var test:Date = _days[i] as Date;
                if (test != null) {
                    if (test.getDate() == d.getDate())
                        return i;
			    }
            }
            return -1;
		}
```

As only a single month is display at a time then you only need to check the year and month once.

**Comment by Harbs** [comment]
That’s not going to work because I believe _days[0] can be null.

There might be a way to make the check a little more performant, but I can’t think of a way to do so without making the code convoluted.

If you are worried about the performance of getDateString() vs separate calls to getMonth(), getDate(), etc, you can create a performance test on https://jsperf.com and we can see what we’re dealing with.

I have other higher priority issues at the moment, but we don’t want to introduce bugs trying to make theoretical performance improvements. My quick tests seem to indicate that toDateString() is pretty quick. I'm not sure my tests are accurate, but if they are, it looks like 30 checks for toDateString() are considerably less than a millisecond.

**Pull request closed without merging**
