### PR TITLE
Add Font awesome icon type

### PR DESCRIPTION
**Pull request by mjesteve**

### CODE REVIEW

**Comment by carlosrovira** [comment]
Hi Maria Jose, please, for next time try to avoid this kind of merge and take a clean branch, since it  makes develop to a dirty branching graph. Thanks :)

**Comment by mjesteve** [comment]
Sorry Carlos, I was not aware. I have updated my fork with the royale fork and then I have messed around when committing the changes but I thought that all that would not go in the commit.
I have it in mind.
Thank you.

**Comment by Harbs** [comment]
@carlosrovira When you merge, you can select "Squash" which cleans up the graph to show a single commit.

**Comment by carlosrovira** [comment]
@mjesteve the best is to create a clean branch updated to avoid this king of things

@Harbs thanks, very useful, I was not aware of that option.

**Pull request merged**
