### PR TITLE
New bead BadgeWithMouseClick,  is a Jewel Badge extension that dispat…

### PR DESCRIPTION
**Pull request by mjesteve**
…ches the MouseClick Event

### CODE REVIEW

**Comment by carlosrovira** [comment]
merged, thanks!

**Comment by mjesteve** [comment]
Carlos, I don't know where to put the example correctly nor would it be okay to put some descriptive text, and I don't want to bother anymore, so I won't upload any ... it's no big deal either.
Thanks for everything.

Hiedra.

**Comment by carlosrovira** [comment]
Hi Maria Jose, I added the simple example here: 
https://github.com/apache/royale-asjs/commit/793715ca70cdba03bf3cb5bf894d4e99f717814f

**Comment by mjesteve** [comment]
Much better where you have put it, I like it.

Hiedra.

**Pull request merged**
